# Generated by Django 4.2.1 on 2023-06-08 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "아침"),
                            ("lunch", "점심"),
                            ("dinner", "저녁"),
                            ("snack", "간식"),
                        ],
                        default="snack",
                        max_length=10,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "custom_serving",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food.customservingunit",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="food.food"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
